#coping file
- name: Copy file to Server1
  hosts: host1
  remote_user: ec2-user  # Adjust as per your EC2 instance's setup
  gather_facts: no

  tasks:
  - name: Copy file to EC2 instance
    copy: 
      src: ./app1.py
      dest: /home/ec2-user/app.py
      owner: ec2-user
      group: ec2-user
      mode: '0777'

#copying file
- name: Copy file to Server2
  hosts: host2
  remote_user: ec2-user  # Adjust as per your EC2 instance's setup
  gather_facts: no

  tasks:
  - name: Copy file to EC2 instance
    copy: 
      src: ./app2.py
      dest: /home/ec2-user/app.py
      owner: ec2-user
      group: ec2-user
      mode: '0777'